INKSCAPE=/usr/bin/inkscape
OPTIPNG=/usr/bin/optipng -o7 --strip all --quiet
SCSS=sassc

DEFAULT_THEME_COLOR=\#2777ff
COLOR_VARIANTS=Blue Green Red Yellow
COLOR_Blue=\#2777ff
TEXT_COLOR_Blue=\#ffffff
COLOR_Green=\#06a284
TEXT_COLOR_Green=\#ffffff
COLOR_Red=\#ec0101
TEXT_COLOR_Red=\#ffffff
COLOR_Yellow=\#ffd86e
TEXT_COLOR_Yellow=\#000000
